import utils
import argparse

ap = argparse.ArgumentParser()
ap.add_argument("-i", "--input", type=str, required=True,
    help="input file, must be a .xml generated by this program", metavar='')
ap.add_argument("-o", "--output", type=str, required=True,
    help="Output file, include the .csv file extension", metavar='')
args = vars(ap.parse_args())

df = utils.dlib_xml_to_pandas(args["input"])
df.to_csv(args["output"])
